---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	resolve_employee(resolve_employee)
	data_retriever_agent(data_retriever_agent)
	retrieval_tool(retrieval_tool)
	report_generator_agent(report_generator_agent)
	__end__([<p>__end__</p>]):::last
	__start__ --> resolve_employee;
	data_retriever_agent --> retrieval_tool;
	resolve_employee --> data_retriever_agent;
	retrieval_tool --> report_generator_agent;
	report_generator_agent --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
